[package]
name = "blockchain-ssd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primitive-types = "0.11.1"
rand = "0.8.5"
chrono = "0.4.19"
sha2 = "0.10.2"
tokio = "1.17.0"